### ISSUE TITLE
Working Directory

### ISSUE THREAD

**Issue by AngeloBestetti** [TWC-Software/DaemonMaster#25]
Recently I was trying to create some service and I just notice DaemonMaster does not have an "Working Directory"

Example:

It´s installed on "C:\Program Files\DaemonMaster"

I need to create a service that run "C:\Program Files\Rscript.exe" with the parameter: "C:\Scripts\test.R"

But there is no "Working Directory", means all the files inside the "C:\Scripts\" it´s not being loaded because DaemonMaster it´s running on another folder.

It´s possible to implement this functionality?

**Comment by MCPC10** [comment]
Hello,
Yeah, actually DaemonMaster use the binary Dir as current Dir when starting a process, so in this case it should be "C:\Program Files\". I can try to change it, but that could take some time because I started to move to the MVVM pattern and now it's a bit of a mess in the code xD. But as a workaround, is it not possible for you to start the process in a .bat file with the path specified?

**Comment by AngeloBestetti** [comment]
That's what I did. I Will wait further updates.

Many thank's, great job

Em qua., 17 de mai. de 2023 15:56, Mike Cremer ***@***.***>
escreveu:

**Comment by MCPC10** [comment]
Finally implement with version 0.2.15.0
